packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - "@a2zb/styles@1.0.3"
  - "@a2zb/lib@1.0.0"
  - "@a2zb/react@1.0.3"
